# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - copyloopvar
    - decorder
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - goconst
    - gocritic
    - godot
    # - godox
    - gofmt
    - gofumpt
    - goimports
    - mnd
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - musttag
    - nilerr
    - nilnil
    - predeclared
    - reassign
    - revive
    - sloglint
    - staticcheck
    - tenv
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
    - wrapcheck
    - wsl

linters-settings:
  goconst:
    min-occurrences: 5
